# On push to main, release a new version of the action using the version in package.json

name: Release Action

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build
        run: |
          npm install
          npm run build

      # Generate a release version
      - name: Prepare Release Version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        shell: bash

      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Construct the release payload
          PAYLOAD=$(jq -n \
          --arg tag_name "v$VERSION" \
          --arg name "Release v$VERSION" \
          '{
            tag_name: $tag_name,
            name: $name,
            draft: false,
            prerelease: false
          }')

          # Make the request, and save the response.
          RESPONSE=$(curl \
            -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "$PAYLOAD")

          # Write UPLOAD_URL to the GITHUB_ENV
          # This makes it directly accessible in the next step.
          UPLOAD_URL=$(echo $RESPONSE | jq -r .upload_url | sed 's/{?name,label}//')
          echo "UPLOAD_URL=${UPLOAD_URL}" >> $GITHUB_ENV

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ASSET_PATH="./dist/index.js"

          # Perform the upload
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/javascript" \
            -H "Accept: application/vnd.github.v3+json" \
            --data-binary @"${ASSET_PATH}" \
            "${UPLOAD_URL}?name=index.js"

      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_DEPLOYMENT_ALERTS }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Analyzer Github Action release completed by '${{ github.actor }}' on branch '${{ github.ref_name }}'."}' \
          $SLACK_WEBHOOK_URL
